---
title: "Data Import"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
library(haven)
```

##read in some data

read in the litters dataset.

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## Take a look at the data

Printing in the console.

```{r}
head(litters_df)
tail(litters_df)
skimr::skim(litters_df)
```

## Options to read_csv
CHECK OUT `?read_csv()` for more information.

litters_df = read_csv("./data/FAS_litters.csv", skip = 10, col_names = FALSE, na=c("","NA",".", 999))


## Other file formats

Read in an excel file.

```{r}
mlb_df = read_excel("./data/mlb11.xlsx", range = "A1:F7")
mlb_df
```
Read in a SAS file.
```{r}
pulse_df = read_sas("./data/public_pulse_data.sas7bdat")
pulse_df = janitor::clean_names(pulse_df)
```
## Cpmparison with Base R
what about `read.csv` ...?

```{r}

litters_base = read.csv("./data/FAS_litters.csv")
litters_readr = read_csv("./data/FAS_litters.csv")

litters_base
litters_readr
```

## Exporting data

export the mlb sub_table.
```{r}

write_csv(mlb_df, "./data/mlb1_suvtable.csv")
```

